config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]

    # 瀏覽所有餐廳的最新動態
    # GET restaurants/feeds
    collection do
      get :feeds

      # 十大人氣餐廳
      get :ranking
    end

    # 瀏覽個別餐廳的 Dashboard
    member do
      get :dashboard
    end

    # 收藏 / 取消收藏
    member do
      post :favorite
      post :unfavorite
    end

    # 喜歡 / 取消喜歡
    member do
      post :like
      post :unlike
    end
  end

  resources :followships, only: [:create, :destroy]
  
  resources :categories, only: [:show]
  resources :users, only: [:index, :show, :edit, :update]
  root "restaurants#index"

  namespace :admin do
  	resources :restaurants
  	resources :categories
  	root "restaurants#index"
  end	

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # 上傳照片 將 AvatarUploader 掛載到 User Model
  mount_uploader :avatar, AvatarUploader

  # 驗證名稱，必須必填
  validates_presence_of :name

  # 如果 User 已經有了評論，就不允許刪除帳號（刪除時拋出 Error）
  has_many :comments, dependent: :restrict_with_error

  # 一個 User 評論過很多 Restaurant，一個 Restaurant 被很多個 User 評論
  has_many :commented_restaurants, through: :comments, source: :restaurant

  # 「使用者收藏很多餐廳」的多對多關聯
  has_many :favorites, dependent: :destroy
  has_many :favorited_restaurants, through: :favorites, source: :restaurant

  # 「使用者喜歡很多餐廳」的多對多關聯
  has_many :likes, dependent: :destroy
  has_many :liked_restaurants, through: :likes, source: :restaurant

  # 「使用者追蹤使用者」的 self-referential relationships 設定
  # 不需要另加 source，Rails 可從 Followship Model 設定來判斷 followings 指向 User Model
  has_many :followships, dependent: :destroy
  has_many :followings, through: :followships

  # 「使用者的追蹤者」的設定
  # 透過 class_name, foreign_key 的自訂，指向 Followship 表上的另一側
  has_many :inverse_followships, class_name: "Followship", foreign_key: "following_id"
  has_many :followers, through: :inverse_followships, source: :user

  def admin?
  	self.role == "admin"
  end

  def following?(user)
    self.followings.include?(user)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :set_user, only: [:show, :edit, :update]

	def index
		@users = User.all
	end

	def show
		# @commented_restaurants = @user.restaurants.uniq #已評論的餐廳
		@commented_restaurants = @user.commented_restaurants.uniq #已評論的餐廳
		@favorited_restaurants = @user.favorited_restaurants
		@followings = @user.followings
		@followers = @user.followers # 需至 User Model 自訂方法
	end

	def edit
		unless @user == current_user
			redirect_to user_path(@user)
		end
	end

	def update
		@user.update(user_params)
		redirect_to user_path(@user)
	end

	private

	def set_user
		@user = User.find(params[:id])
	end

	def user_params
		params.require(:user).permit(:name, :intro, :avatar)
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">

			<h3>Edit Profile</h3>
			<%= form_for @user do |f| %>
				<div class="form-group">
					<%= f.label :name, "Name" %>
					<%= f.text_field :name, class: "form-control" %>
				</div>
				<div class="form-group">
					<%= f.label :intro, "自我介紹" %>
					<%= f.text_area :intro, class: "form-control" %>
				</div>
				<div class="form-group">
					<%= f.label :avatar, "大頭照上傳" %>
					<%= image_tag @user.avatar if @user.avatar? %>
					<%= f.file_field :avatar %>
				</div>
				<div class="form-group">
					<%= f.submit "Update", class: "btn btn-warning" %>
					<%= link_to "Cancel", user_path(@user), class: "btn btn-default" %>
				</div>
			<% end %>

		</div>
	</div>
</div>

app/views/users/index.html.erb
<div class="container">
	<div class="row">

		<ul class="nav nav-tabs">
			<li role="presentation" >
				<%= link_to '首頁', root_path %>
			</li>
			<li role="presentation">
				<%= link_to '最新動態' %>
			</li>
			<li role="presentation">
				<%= link_to 'TOP10人氣餐廳', ranking_restaurants_path %>
			</li>
			<li role="presentation" class="active">
				<%= link_to '美食達人', users_path %>
			</li>
		</ul>

	</div>
</div>

<div class="container">
	<div class="row">

		<div class="col-md-12">
			<div class="page-header">
				<h1>美食達人</h1>
			</div>
		</div>
		<% @users.each do |user| %>
			<div class="col-md-3 col-sm-4 col-xs-6 text-center user-item">
				<%= link_to user_path(user) do %>
					<!-- 使用blank?判斷avatar欄位為空值或nil時皆會回傳false -->
					<% if user.avatar.blank? %>
						<img src="http://via.placeholder.com/128x128">
					<% else %>
						<%= image_tag user.avatar, class: "img-rounded" %>
					<% end %>
					<h4><%= user.name %></h4>
				<% end %>
				<%= render partial: "shared/follow", locals: {user: user} %>
			</div>
		<% end %>

	</div>
</div>

app/views/users/show.html.erb
<div class="container">
	<div class="row">
		
		<div class="col-md-10 col-md-offset-1">
			<!-- page-header 裡面顯示個人檔案資料 -->
			<div class="page-header">
				<div class="col-md-3 col-sm-4">
					<div class="text-center">
						<%= image_tag @user.avatar, class: "img-responsive img-rounded" %>
					</div>
				</div>
				<div class="col-md-9 col-sm-8">
					<h2><%= @user.name %></h2>
					<p><strong><%= @user.email %></strong></p>
					<!-- inline & unstyled 的 list -->
		           	<ul class="list-unstyled list-inline">
			            <li><strong><%= @commented_restaurants.count %></strong> 已評論餐廳</li>
			            <li><strong><%= @favorited_restaurants.count %></strong> 收藏的餐廳</li>
			            <li><strong><%= @followings.count %></strong> followings</li>
			            <li><strong><%= @followers.count %></strong> followers</li>
		           	</ul>
					<div><%= simple_format @user.intro %></div>
					<% if @user.email == current_user.email %>
						<%= link_to 'Edit Profile', edit_user_path(@user), class: "btn btn-warning" %>
					<% end %>
				</div>
				<div class="clearfix"></div>
			</div>
			<br>
			<div class="col-md-4">
				<!-- 顯示followings的清單，panel包一個list-group  -->
				<div class="panel panel-default">
					<div class="panel-heading">
						<h3 class="panel-title"><%= @followings.count %></strong> followings</h3>
					</div>
					<ul class="list-group">
						<% @followings.each do |following| %>
							<li class="list-group-item">
								<%= link_to user_path(following) do %>
									<%= image_tag(following.avatar, height: 30, width: 30, class: "img-circle") %>
									<%= following.name %>
								<% end %>
							</li>
						<% end %>
					</ul>
				</div>
				<!-- 顯示followers的清單，panel包一個list-group  -->
				<div class="panel panel-default">
					<div class="panel-heading">
						<h3 class="panel-title"><%= @followers.count %></strong> followers</h3>
					</div>

					<ul class="list-group">
						<% @followers.each do |follower| %>
							<li class="list-group-item">
								<%= link_to user_path(follower) do %>
									<%= image_tag(follower.avatar, height: 30, width: 30, class: "img-circle") %>
									<%= follower.name %>
								<% end %>
							</li>
						<% end %>
					</ul>
				</div>
			</div>
       		<div class="col-md-8">
				<!-- 顯示已評論餐廳的清單，panel包一個panel-body裡面使用row>col的layouts來顯示評論 -->
				<div class="panel panel-default">
					<div class="panel-heading">
						<h3 class="panel-title"><strong><%= @commented_restaurants.count %></strong>已評論餐廳</h3>
					</div>
					<div class="panel-body">
						<% @commented_restaurants.each do |restaurant| %>
							<%= link_to restaurant_path(restaurant) do %>
								<div class="my-restaurant">
									<div>
										<%= image_tag restaurant.image, class: "img-responsive img-rounded" %>
									</div>
									<h5><%= restaurant.name %></h5>
								</div>
							<% end %>
						<% end %>
					</div>
				</div>
				<!-- 顯示收藏的餐廳的清單，panel包一個panel-body裡面簡單顯示餐廳圖片和name -->
         		<div class="panel panel-default">
		        	<div class="panel-heading">
		             	<h3 class="panel-title"><strong><%= @favorited_restaurants.count %></strong> 收藏的餐廳</h3>
		           	</div>
 
           			<div class="panel-body">
             			<% @favorited_restaurants.each do |restaurant| %>
               				<div class="my-restaurant">
                 				<div>
                   					<%= link_to restaurant_path(restaurant) do %>
	                     				<%= image_tag restaurant.image, class: "img-responsive img-rounded" %>
	                     				<h5><%= restaurant.name %></h5>
                   					<% end %>
                 				</div>
               				</div>
             			<% end %>
           			</div>
         		</div>
			</div>
		</div>

	</div>
</div>