config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]

    # 瀏覽所有餐廳的最新動態
    # GET restaurants/feeds
    collection do
      get :feeds

      # 十大人氣餐廳
      get :ranking
    end

    # 瀏覽個別餐廳的 Dashboard
    member do
      get :dashboard
    end

    # 收藏 / 取消收藏
    member do
      post :favorite
      post :unfavorite
    end

    # 喜歡 / 取消喜歡
    member do
      post :like
      post :unlike
    end
  end

  resources :followships, only: [:create, :destroy]
  
  resources :categories, only: [:show]
  resources :users, only: [:index, :show, :edit, :update]
  root "restaurants#index"

  namespace :admin do
  	resources :restaurants
  	resources :categories
  	root "restaurants#index"
  end	

end

app/views/shared/_favorite.html.erb
<% if restaurant.is_favorited?(current_user) %>
	<%= link_to 'Unfavorite', unfavorite_restaurant_path(restaurant), method: :post, class: "btn btn-info" %>
<% else %>
	<%= link_to 'Favorite', favorite_restaurant_path(restaurant), method: :post, class: "btn btn-warning" %>
<% end %>	

app/views/shared/_follow.html.erb
<% if user != current_user %>
	<% if current_user.following?(user) %>
		<!-- 會用 DELETE 動作導向 http://localhost:3000/followships/{user.id} -->
		<%= link_to 'Unfollow', followship_path(user), method: :delete , class: "btn btn-link" %>
	<% else %>
		<!-- 會用 POST 動作導向 http://localhost:3000/followships?following_id={user.id} -->
		<%= link_to 'Follow', followships_path(following_id: user), method: :post, class: "btn btn-default" %>
	<% end %>
<% end %>

app/views/shared/_like.html.erb
<% if restaurant.is_liked?(current_user) %>
	<%= link_to 'Unlike', unlike_restaurant_path(restaurant), method: :pose, class: "btn btn-info" %>
<% else %>
	<%= link_to 'Like', like_restaurant_path(restaurant), method: :post, class: "btn btn-warning" %>
<% end %>

app/views/shared/_restaurant_list.html.erb
<!-- restaurants list，有多寫restaurant-item的class style -->
<% @restaurants.each do |restaurant| %>
  <div class="col-sm-6 col-md-4">
    <div class="restaurant-item">
      <%= image_tag restaurant.image, class: "img-responsive center-block" %>
      <div class="caption">
        <h3><%= link_to restaurant.name, restaurant_path(restaurant) %></h3>
        <p class="label label-primary"><%= restaurant.category.name %><p>
        <p><%= truncate(restaurant.description, length: 80) %></p>
        <%= render partial: "shared/favorite", locals: {restaurant: restaurant} %>
        <%= render partial: "shared/like", locals: {restaurant: restaurant} %>
      </div>
    </div>
  </div>
<% end %>

<!-- 有generate kaminari paginate bootstrap style -->
<div class="text-center">
  <%= paginate @restaurants %>
</div>